variable "cidr" {}
variable "dns_zone_name" {}
variable "env_name" {}
variable "env_short_name" {}
variable "external_db" {}
variable "location" {}
variable "resource_group_name" {}
variable "network_name" {}
variable "postgres_username" {}
