product-name: pivotal-container-service
network-properties:
  network:
    name: {{ .pks_subnet_name }}
  service_network:
    name: {{ .services_subnet_name }}
  other_availability_zones:
    {{range .azs}}
    - name: {{.}}
    {{end}}
  singleton_availability_zone:
    name: {{index .azs 0}}
product-properties:
  .pivotal-container-service.pks_tls:
    value:
        cert_pem: |
{{indent 10 .ssl_cert}}
        private_key_pem: |
{{indent 10 .ssl_private_key}}
  .properties.pks_api_hostname:
    value: {{.pks_api_endpoint}}
  .properties.plan1_selector.active.master_vm_type:
    value: Standard_F2s
  .properties.plan1_selector.active.worker_vm_type:
    value: Standard_F2s
  .properties.plan1_selector.active.errand_vm_type:
    value: Standard_F2s
  .properties.plan1_selector.active.master_az_placement:
    value:
    - {{index .azs 0}}
  .properties.plan1_selector.active.worker_az_placement:
    value:
    {{range .azs}}
    - {{.}}
    {{end}}
  .properties.plan2_selector:
    value: "Plan Inactive"
  .properties.plan3_selector:
    value: "Plan Inactive"
  .properties.cloud_provider:
    value: Azure
  .properties.cloud_provider.azure.subscription_id:
    value: {{.subscription_id}}
  .properties.cloud_provider.azure.tenant_id:
    value: {{.tenant_id}}
  .properties.cloud_provider.azure.location:
    value: {{.location}}
  .properties.cloud_provider.azure.resource_group_name:
    value: {{.resource_group_name}}
  .properties.cloud_provider.azure.vnet_name:
    value: {{.vnet_name}}
  .properties.cloud_provider.azure.vnet_resource_group_name:
    value: {{.vnet_resource_group_name}}
  .properties.cloud_provider.azure.default_security_group:
    value: {{.default_security_group}}
  .properties.cloud_provider.azure.primary_availability_set:
    value: {{.primary_availability_set}}
  .properties.cloud_provider.azure.azure_master_managed_identity:
    value: {{.azure_master_managed_identity}}
  .properties.cloud_provider.azure.azure_worker_managed_identity:
    value: {{.azure_worker_managed_identity}}
  .properties.telemetry_selector:
    value: disabled
resource-config:
  pivotal-container-service:
    elb_names:
    - {{.pks_lb_name}}
errand-config:
  smoke-tests:
    post-deploy-state: true
